/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package first.java;

import org.junit.Test;
import static org.junit.Assert.*;

public class AccountTest {
    @Test public void testAccountHasABalance() {
        Account obj = new Account();
        assertEquals(0.00, obj.balance, 0.00);
        assertEquals(0.00, obj.overdraft, 0.00);
    }
}
